/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ReservaCateringRouteImport } from './routes/reserva-catering'
import { Route as ReservarCateringRouteImport } from './routes/reservar-catering'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as AuthenticatedAdminCateringRouteImport } from './routes/_authenticated/admin-catering'
import { Route as AuthenticatedAdminClientesRouteImport } from './routes/_authenticated/admin-clientes'
import { Route as AuthenticatedAdminClubRouteImport } from './routes/_authenticated/admin-club'
import { Route as AuthenticatedAdminClubContenidoRouteImport } from './routes/_authenticated/admin-club-contenido'
import { Route as AuthenticatedAdminCodigosRouteImport } from './routes/_authenticated/admin-codigos'
import { Route as AuthenticatedAdminCursosRouteImport } from './routes/_authenticated/admin-cursos'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin-productos'
import { Route as AuthenticatedAdminPromocionesRouteImport } from './routes/_authenticated/admin-promociones'
import { Route as AuthenticatedAdminSucursalesRouteImport } from './routes/_authenticated/admin-sucursales'
import { Route as AuthenticatedAdminTiendaSeccionRouteImport } from './routes/_authenticated/admin-tienda-seccion'
import { Route as AuthenticatedAdminVentasRouteImport } from './routes/_authenticated/admin-ventas'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as AuthenticatedCursosRouteImport } from './routes/_authenticated/cursos'
import { Route as AuthenticatedPromocionesRouteImport } from './routes/_authenticated/promociones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaCateringRoute = ReservaCateringRouteImport.update({
  id: '/reserva-catering',
  path: '/reserva-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarCateringRoute = ReservarCateringRouteImport.update({
  id: '/reservar-catering',
  path: '/reservar-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCateringRoute =
  AuthenticatedAdminCateringRouteImport.update({
    id: '/admin-catering',
    path: '/admin-catering',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClientesRoute =
  AuthenticatedAdminClientesRouteImport.update({
    id: '/admin-clientes',
    path: '/admin-clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminClubRoute = AuthenticatedAdminClubRouteImport.update({
  id: '/admin-club',
  path: '/admin-club',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminClubContenidoRoute =
  AuthenticatedAdminClubContenidoRouteImport.update({
    id: '/admin-club-contenido',
    path: '/admin-club-contenido',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCodigosRoute =
  AuthenticatedAdminCodigosRouteImport.update({
    id: '/admin-codigos',
    path: '/admin-codigos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCursosRoute =
  AuthenticatedAdminCursosRouteImport.update({
    id: '/admin-cursos',
    path: '/admin-cursos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/admin-productos',
    path: '/admin-productos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPromocionesRoute =
  AuthenticatedAdminPromocionesRouteImport.update({
    id: '/admin-promociones',
    path: '/admin-promociones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSucursalesRoute =
  AuthenticatedAdminSucursalesRouteImport.update({
    id: '/admin-sucursales',
    path: '/admin-sucursales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTiendaSeccionRoute =
  AuthenticatedAdminTiendaSeccionRouteImport.update({
    id: '/admin-tienda-seccion',
    path: '/admin-tienda-seccion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminVentasRoute =
  AuthenticatedAdminVentasRouteImport.update({
    id: '/admin-ventas',
    path: '/admin-ventas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCursosRoute = AuthenticatedCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromocionesRoute =
  AuthenticatedPromocionesRouteImport.update({
    id: '/promociones',
    path: '/promociones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reserva-catering': typeof ReservaCateringRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/admin-catering': typeof AuthenticatedAdminCateringRoute
  '/admin-clientes': typeof AuthenticatedAdminClientesRoute
  '/admin-club': typeof AuthenticatedAdminClubRoute
  '/admin-club-contenido': typeof AuthenticatedAdminClubContenidoRoute
  '/admin-codigos': typeof AuthenticatedAdminCodigosRoute
  '/admin-cursos': typeof AuthenticatedAdminCursosRoute
  '/admin-productos': typeof AuthenticatedAdminProductosRoute
  '/admin-promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin-sucursales': typeof AuthenticatedAdminSucursalesRoute
  '/admin-tienda-seccion': typeof AuthenticatedAdminTiendaSeccionRoute
  '/admin-ventas': typeof AuthenticatedAdminVentasRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/promociones': typeof AuthenticatedPromocionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reserva-catering': typeof ReservaCateringRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/admin-catering': typeof AuthenticatedAdminCateringRoute
  '/admin-clientes': typeof AuthenticatedAdminClientesRoute
  '/admin-club': typeof AuthenticatedAdminClubRoute
  '/admin-club-contenido': typeof AuthenticatedAdminClubContenidoRoute
  '/admin-codigos': typeof AuthenticatedAdminCodigosRoute
  '/admin-cursos': typeof AuthenticatedAdminCursosRoute
  '/admin-productos': typeof AuthenticatedAdminProductosRoute
  '/admin-promociones': typeof AuthenticatedAdminPromocionesRoute
  '/admin-sucursales': typeof AuthenticatedAdminSucursalesRoute
  '/admin-tienda-seccion': typeof AuthenticatedAdminTiendaSeccionRoute
  '/admin-ventas': typeof AuthenticatedAdminVentasRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/cursos': typeof AuthenticatedCursosRoute
  '/promociones': typeof AuthenticatedPromocionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reserva-catering': typeof ReservaCateringRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/_authenticated/admin-catering': typeof AuthenticatedAdminCateringRoute
  '/_authenticated/admin-clientes': typeof AuthenticatedAdminClientesRoute
  '/_authenticated/admin-club': typeof AuthenticatedAdminClubRoute
  '/_authenticated/admin-club-contenido': typeof AuthenticatedAdminClubContenidoRoute
  '/_authenticated/admin-codigos': typeof AuthenticatedAdminCodigosRoute
  '/_authenticated/admin-cursos': typeof AuthenticatedAdminCursosRoute
  '/_authenticated/admin-productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin-promociones': typeof AuthenticatedAdminPromocionesRoute
  '/_authenticated/admin-sucursales': typeof AuthenticatedAdminSucursalesRoute
  '/_authenticated/admin-tienda-seccion': typeof AuthenticatedAdminTiendaSeccionRoute
  '/_authenticated/admin-ventas': typeof AuthenticatedAdminVentasRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/_authenticated/cursos': typeof AuthenticatedCursosRoute
  '/_authenticated/promociones': typeof AuthenticatedPromocionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reserva-catering'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/admin-catering'
    | '/admin-clientes'
    | '/admin-club'
    | '/admin-club-contenido'
    | '/admin-codigos'
    | '/admin-cursos'
    | '/admin-productos'
    | '/admin-promociones'
    | '/admin-sucursales'
    | '/admin-tienda-seccion'
    | '/admin-ventas'
    | '/cuenta'
    | '/cursos'
    | '/promociones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reserva-catering'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/admin-catering'
    | '/admin-clientes'
    | '/admin-club'
    | '/admin-club-contenido'
    | '/admin-codigos'
    | '/admin-cursos'
    | '/admin-productos'
    | '/admin-promociones'
    | '/admin-sucursales'
    | '/admin-tienda-seccion'
    | '/admin-ventas'
    | '/cuenta'
    | '/cursos'
    | '/promociones'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reserva-catering'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/tienda'
    | '/_authenticated/admin-catering'
    | '/_authenticated/admin-clientes'
    | '/_authenticated/admin-club'
    | '/_authenticated/admin-club-contenido'
    | '/_authenticated/admin-codigos'
    | '/_authenticated/admin-cursos'
    | '/_authenticated/admin-productos'
    | '/_authenticated/admin-promociones'
    | '/_authenticated/admin-sucursales'
    | '/_authenticated/admin-tienda-seccion'
    | '/_authenticated/admin-ventas'
    | '/_authenticated/cuenta'
    | '/_authenticated/cursos'
    | '/_authenticated/promociones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ClubRoute: typeof ClubRoute
  ReservaCateringRoute: typeof ReservaCateringRoute
  ReservarCateringRoute: typeof ReservarCateringRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva-catering': {
      id: '/reserva-catering'
      path: '/reserva-catering'
      fullPath: '/reserva-catering'
      preLoaderRoute: typeof ReservaCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar-catering': {
      id: '/reservar-catering'
      path: '/reservar-catering'
      fullPath: '/reservar-catering'
      preLoaderRoute: typeof ReservarCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-catering': {
      id: '/_authenticated/admin-catering'
      path: '/admin-catering'
      fullPath: '/admin-catering'
      preLoaderRoute: typeof AuthenticatedAdminCateringRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-clientes': {
      id: '/_authenticated/admin-clientes'
      path: '/admin-clientes'
      fullPath: '/admin-clientes'
      preLoaderRoute: typeof AuthenticatedAdminClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-club': {
      id: '/_authenticated/admin-club'
      path: '/admin-club'
      fullPath: '/admin-club'
      preLoaderRoute: typeof AuthenticatedAdminClubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-club-contenido': {
      id: '/_authenticated/admin-club-contenido'
      path: '/admin-club-contenido'
      fullPath: '/admin-club-contenido'
      preLoaderRoute: typeof AuthenticatedAdminClubContenidoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-codigos': {
      id: '/_authenticated/admin-codigos'
      path: '/admin-codigos'
      fullPath: '/admin-codigos'
      preLoaderRoute: typeof AuthenticatedAdminCodigosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-cursos': {
      id: '/_authenticated/admin-cursos'
      path: '/admin-cursos'
      fullPath: '/admin-cursos'
      preLoaderRoute: typeof AuthenticatedAdminCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-productos': {
      id: '/_authenticated/admin-productos'
      path: '/admin-productos'
      fullPath: '/admin-productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-promociones': {
      id: '/_authenticated/admin-promociones'
      path: '/admin-promociones'
      fullPath: '/admin-promociones'
      preLoaderRoute: typeof AuthenticatedAdminPromocionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-sucursales': {
      id: '/_authenticated/admin-sucursales'
      path: '/admin-sucursales'
      fullPath: '/admin-sucursales'
      preLoaderRoute: typeof AuthenticatedAdminSucursalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-tienda-seccion': {
      id: '/_authenticated/admin-tienda-seccion'
      path: '/admin-tienda-seccion'
      fullPath: '/admin-tienda-seccion'
      preLoaderRoute: typeof AuthenticatedAdminTiendaSeccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-ventas': {
      id: '/_authenticated/admin-ventas'
      path: '/admin-ventas'
      fullPath: '/admin-ventas'
      preLoaderRoute: typeof AuthenticatedAdminVentasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cursos': {
      id: '/_authenticated/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof AuthenticatedCursosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promociones': {
      id: '/_authenticated/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof AuthenticatedPromocionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminCateringRoute: typeof AuthenticatedAdminCateringRoute
  AuthenticatedAdminClientesRoute: typeof AuthenticatedAdminClientesRoute
  AuthenticatedAdminClubRoute: typeof AuthenticatedAdminClubRoute
  AuthenticatedAdminClubContenidoRoute: typeof AuthenticatedAdminClubContenidoRoute
  AuthenticatedAdminCodigosRoute: typeof AuthenticatedAdminCodigosRoute
  AuthenticatedAdminCursosRoute: typeof AuthenticatedAdminCursosRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminPromocionesRoute: typeof AuthenticatedAdminPromocionesRoute
  AuthenticatedAdminSucursalesRoute: typeof AuthenticatedAdminSucursalesRoute
  AuthenticatedAdminTiendaSeccionRoute: typeof AuthenticatedAdminTiendaSeccionRoute
  AuthenticatedAdminVentasRoute: typeof AuthenticatedAdminVentasRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
  AuthenticatedCursosRoute: typeof AuthenticatedCursosRoute
  AuthenticatedPromocionesRoute: typeof AuthenticatedPromocionesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminCateringRoute: AuthenticatedAdminCateringRoute,
  AuthenticatedAdminClientesRoute: AuthenticatedAdminClientesRoute,
  AuthenticatedAdminClubRoute: AuthenticatedAdminClubRoute,
  AuthenticatedAdminClubContenidoRoute: AuthenticatedAdminClubContenidoRoute,
  AuthenticatedAdminCodigosRoute: AuthenticatedAdminCodigosRoute,
  AuthenticatedAdminCursosRoute: AuthenticatedAdminCursosRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminPromocionesRoute: AuthenticatedAdminPromocionesRoute,
  AuthenticatedAdminSucursalesRoute: AuthenticatedAdminSucursalesRoute,
  AuthenticatedAdminTiendaSeccionRoute: AuthenticatedAdminTiendaSeccionRoute,
  AuthenticatedAdminVentasRoute: AuthenticatedAdminVentasRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
  AuthenticatedCursosRoute: AuthenticatedCursosRoute,
  AuthenticatedPromocionesRoute: AuthenticatedPromocionesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ClubRoute: ClubRoute,
  ReservaCateringRoute: ReservaCateringRoute,
  ReservarCateringRoute: ReservarCateringRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
