/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ReservarCateringRouteImport } from './routes/reservar-catering'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SucursalesRouteImport } from './routes/sucursales'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as AuthenticatedAdminClubRouteImport } from './routes/_authenticated/admin-club'
import { Route as AuthenticatedCuentaRouteImport } from './routes/_authenticated/cuenta'
import { Route as ApiPagosnetWebhookRouteImport } from './routes/api.pagosnet-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarCateringRoute = ReservarCateringRouteImport.update({
  id: '/reservar-catering',
  path: '/reservar-catering',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SucursalesRoute = SucursalesRouteImport.update({
  id: '/sucursales',
  path: '/sucursales',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminClubRoute = AuthenticatedAdminClubRouteImport.update({
  id: '/admin-club',
  path: '/admin-club',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCuentaRoute = AuthenticatedCuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPagosnetWebhookRoute = ApiPagosnetWebhookRouteImport.update({
  id: '/api/pagosnet-webhook',
  path: '/api/pagosnet-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucursales': typeof SucursalesRoute
  '/tienda': typeof TiendaRoute
  '/admin-club': typeof AuthenticatedAdminClubRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/api/pagosnet-webhook': typeof ApiPagosnetWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucursales': typeof SucursalesRoute
  '/tienda': typeof TiendaRoute
  '/admin-club': typeof AuthenticatedAdminClubRoute
  '/cuenta': typeof AuthenticatedCuentaRoute
  '/api/pagosnet-webhook': typeof ApiPagosnetWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/club': typeof ClubRoute
  '/reservar-catering': typeof ReservarCateringRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sucursales': typeof SucursalesRoute
  '/tienda': typeof TiendaRoute
  '/_authenticated/admin-club': typeof AuthenticatedAdminClubRoute
  '/_authenticated/cuenta': typeof AuthenticatedCuentaRoute
  '/api/pagosnet-webhook': typeof ApiPagosnetWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sucursales'
    | '/tienda'
    | '/admin-club'
    | '/cuenta'
    | '/api/pagosnet-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sucursales'
    | '/tienda'
    | '/admin-club'
    | '/cuenta'
    | '/api/pagosnet-webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/club'
    | '/reservar-catering'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sucursales'
    | '/tienda'
    | '/_authenticated/admin-club'
    | '/_authenticated/cuenta'
    | '/api/pagosnet-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ClubRoute: typeof ClubRoute
  ReservarCateringRoute: typeof ReservarCateringRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SucursalesRoute: typeof SucursalesRoute
  TiendaRoute: typeof TiendaRoute
  ApiPagosnetWebhookRoute: typeof ApiPagosnetWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar-catering': {
      id: '/reservar-catering'
      path: '/reservar-catering'
      fullPath: '/reservar-catering'
      preLoaderRoute: typeof ReservarCateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sucursales': {
      id: '/sucursales'
      path: '/sucursales'
      fullPath: '/sucursales'
      preLoaderRoute: typeof SucursalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin-club': {
      id: '/_authenticated/admin-club'
      path: '/admin-club'
      fullPath: '/admin-club'
      preLoaderRoute: typeof AuthenticatedAdminClubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cuenta': {
      id: '/_authenticated/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof AuthenticatedCuentaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/pagosnet-webhook': {
      id: '/api/pagosnet-webhook'
      path: '/api/pagosnet-webhook'
      fullPath: '/api/pagosnet-webhook'
      preLoaderRoute: typeof ApiPagosnetWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminClubRoute: typeof AuthenticatedAdminClubRoute
  AuthenticatedCuentaRoute: typeof AuthenticatedCuentaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminClubRoute: AuthenticatedAdminClubRoute,
  AuthenticatedCuentaRoute: AuthenticatedCuentaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ClubRoute: ClubRoute,
  ReservarCateringRoute: ReservarCateringRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SucursalesRoute: SucursalesRoute,
  TiendaRoute: TiendaRoute,
  ApiPagosnetWebhookRoute: ApiPagosnetWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
